source 'https://cdn.cocoapods.org'
source 'https://gitee.com/jingshionline/jsolspecs.git'

use_frameworks!

platform :ios, '9.0'

target 'ADMine_Example' do
  pod 'ADMine', :path => '../'

  target 'ADMine_Tests' do
    inherit! :search_paths

    
  end
end
